// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANloUhGRGhkSCY54EC5dzcDBQYG_G9JBo',
    appId: '1:917996314546:web:968998cb8a986ffa93ceab',
    messagingSenderId: '917996314546',
    projectId: 'flashchat-b5db2',
    authDomain: 'flashchat-b5db2.firebaseapp.com',
    databaseURL: 'https://flashchat-b5db2.firebaseio.com',
    storageBucket: 'flashchat-b5db2.appspot.com',
    measurementId: 'G-38F8P011PQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS2tvcQ7F-umS4NyFAwBcOvSL2W83Z1Es',
    appId: '1:917996314546:android:78cbcd3a14c5f25893ceab',
    messagingSenderId: '917996314546',
    projectId: 'flashchat-b5db2',
    databaseURL: 'https://flashchat-b5db2.firebaseio.com',
    storageBucket: 'flashchat-b5db2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYWqPNNBmXFjMzd6lW3aDK3ATrsE5w-ec',
    appId: '1:917996314546:ios:1c699b46a1f6d91893ceab',
    messagingSenderId: '917996314546',
    projectId: 'flashchat-b5db2',
    databaseURL: 'https://flashchat-b5db2.firebaseio.com',
    storageBucket: 'flashchat-b5db2.appspot.com',
    iosClientId: '917996314546-ah4eeqb480r6qlfctdbdmotmpkkorb3v.apps.googleusercontent.com',
    iosBundleId: 'com.serina.serina',
  );
}
